export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const GET_A_USER_LIST =   'GET_A_USER_LIST'
export const CURRENT_USER_INFO = 'CURRENT_USER_INFO'
export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_RECENT_POSTS = 'GET_RECENT_POSTS'
export const GET_POSTS = 'GET_POSTS'
export const GET_ALL_USERS = 'GET_ALL_USERS'
export const GET_LATEST_POSTS = 'GET_LATEST_POSTS'
export const GET_FEATURED_POSTS = 'GET_FEATURED_POSTS'
export const GET_ACTIVITIES = 'GET_ACTIVITIES'
export const GET_RECENT_TRASH_POSTS = 'GET_RECENT_TRASH_POSTS'
export const GET_FEATURED_TRASH_POSTS = 'GET_FEATURED_TRASH_POSTS'
export const GET_TRASH_POSTS = "GET_TRASH_POSTS"
export const GET_ADS = 'GET_ADS'
//Notification types
export const GET_COMPLETED_NOTIFICATIONS = 'GET_COMPLETED_NOTIFICATIONS'
export const GET_SCHEDULED_NOTIFICATIONS = 'GET_SCHEDULED_NOTIFICATIONS'
export const GET_FAILED_NOTIFICATIONS = 'GET_FAILED_NOTIFICATIONS'
//Analytics
export const GET_USER_MONTHLY_POSTS = 'GET_USER_MONTHLY_POSTS'
export const GET_USER_WEEKLY_POSTS = 'GET_USER_WEEKLY_POSTS'
export const GET_MONTHLY_POSTS = ' GET_MONTHLY_POSTS'
export const GET_USER_UPLOADS = 'GET_USER_UPLOADS'
export const GET_USERS_HITS = 'GET_USER_HITS'
export const GET_USER_ID = 'GET_USER_ID'
export const GET_MONTHLY_NOTIFICATIONS = ' GET_MONTHLY_NOTIFICATIONS'
export const GET_MONTHLY_FAILED_NOTIFICATION = 'GET_MONTHLY_FAILED_NOTIFICATION'
export const GET_USER_TODAY_UPLOADS = 'GET_USER_TODAY_UPLOADS'

export const GET_GLOBAL_STATS = 'GET_GLOBAL_STATS'
export const GET_TOP_POSTS = 'GET_TOP_POSTS'
export const GET_USERMONTHLY_UPLOADS = 'GET_USERMONTHLY_UPLOADS'
export const GET_USERWEEKLY_UPLOADS = 'GET_USERWEEKLY_UPLOADS'
export const SET_POST = 'SET_POST'
export const SET_SELECT_USER = "SET_SELECT_USER"
//Ads cms
export const GET_ADS_CATEGORIES = 'GET_ADS_CATEGORIES'
export const GET_GENERAL_ADS = 'GET_GENERAL_ADS'
export const GET_ADVERTISERS = 'GET_ADVERTISERS'
export const GET_MY_ADS = 'GET_MY_ADS'
//Ads cms graphs
export const MONTHLY_AD_CLICKS = 'MONTHLY_AD_CLICKS'
export const WEEKLY_AD_CLICKS = 'WEEKLY_AD_CLICKS'
export const USER_MONTHLY_AD_CLICKS = 'MONTHLY_AD_CLICKS'
export const USER_WEEKLY_AD_CLICKS = 'WEEKLY_AD_CLICKS'
export const DAILY_AD_CLICKS = 'DAILY_AD_CLICKS'
export const TOTAL_AD_CLICKS = 'TOTAL_AD_CLICKS'


//new types
export const GET_DEVICE_LIST = 'GET_DEVICE_LIST'
export const GET_CARD_LIST = 'GET_CARD_LIST'
export const GET_USER_LIST = 'GET_DEVICE_LIST'
export const GET_ALL_DEVICE_LIST = 'GET_ALL_DEVICE_LIST'

export const GET_PRESENT_LOGS = 'GET_PRESENT_LOGS'
export const GET_EARLYLEAVE_LOGS = 'GET_EARLYLEAVE_LOGSS'
export const GET_COMPLETED_LOGS = 'GET_COMPLETED_LOGS'